### ISSUE TITLE
ubt16.04 fix

### ISSUE THREAD

**Issue by backahasten** [Eventide/openkeeper-cli#26]
#!/bin/bash

sed -i 's/\/usr\/sbin\/ok-start/ok-start/' `which ok`

sed -i 's/${exec_prefix}\/sbin\/ok-connect/ok-connect/' `which ok-start`

echo "Done!"

exit 0

**Comment by RainMark** [comment]
Just execute this command.

```
sudo sed -i 's/\/usr\/sbin\/ok-start/ok-start/' `which ok` && sudo sed -i 's/${exec_prefix}\/sbin\/ok-connect/ok-connect/' `which ok-start`
```

**Comment by RainMark** [comment]
+ 这个问题已经不存在了，可以关闭了。
