### ISSUE TITLE
Could this be compiled in arm architecture?

### ISSUE THREAD

**Issue by caiqiqi** [Eventide/openkeeper-cli#29]
Nice job! I want to clone this repository into my raspberrypi machine, so I wonder if this could be compiled in that platform. Previously I used this [openkeeper](https://github.com/purpleroc/OpenKeeper), but I didnt know why it suddently turned to be unavailable. I just typed `sudo ok`, and it just keeps reconnecting and reconnecting, and failed. I noticed that that one uses C++, while you use c.

**Comment by Eventide** [comment]
You can compile it on rpi.

于 2017年1月16日 GMT+08:00 下午9:54:25, Cai Qiqi <notifications@github.com> 写到:
>Nice job! I want to clone this repository into my raspberrypi machine,
>so I wonder if this could be compiled in that platform. Previously I
>used this [openkeeper](https://github.com/purpleroc/OpenKeeper), but I
>didnt know why it suddently turned to be unavailable. I just typed
>`sudo ok`, and it just keeps reconnecting and reconnecting, and failed.
>I noticed that that one uses C++, while you use c.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Eventide/openkeeper-cli/issues/29

-- 
使用 K-9 Mail 发送自我的Android设备。
