### ISSUE TITLE
ubuntu 16.04 出现错误！！

### ISSUE THREAD

**Issue by sunyuan300** [Eventide/openkeeper-cli#31]
/usr/local/bin/ok: 行 37: m4: 未找到命令
/usr/local/bin/ok: 行 38: m4: 未找到命令
Device "ppp0" does not exist.

**Comment by RainMark** [comment]
`which m4`
If m4 not exist, please install it.

**Comment by RainMark** [comment]
@sunyuan300 
Run this command in terminal.
`which m4`
If m4 not exist, please install it.

**Comment by sunyuan300** [comment]
In this way,I have sovled it ,thank you very much!

**Comment by AaronWharton** [comment]
I got the same problem above, but when I tried '''which m4''' I got nothing. BTW, which should I chose between enp2s0 and wlp3s0? I use ubuntu16.04 and I am in CQUPT. Thanks for your reply.

**Comment by AaronWharton** [comment]
sorry, it may has some error, I have connected it successfully by insatll m4.
