### ISSUE TITLE
这个停止维护一年了，现在还能用么

### ISSUE THREAD

**Issue by xiaxiaxiaxia** [Eventide/openkeeper-cli#39]
这个停止维护一年了，现在还能用么，如果不能用了，我想问下，现在linux端，有什么能够代替的么

**Comment by RainMark** [comment]
@xiaxiaxiaxia 暂时不能直接用了

**Comment by xiaxiaxiaxia** [comment]
很期待再更新呢，很不错的项目

**Comment by RainMark** [comment]
@xiaxiaxiaxia 没办法更新了，电信出新版本客户端，加了强壳，暂时逆向不出算法。建议使用电信官方客户端。

**Comment by FanGeV5** [comment]
现在不能用了吗
